# US Electric Vehicle & Renewable Energy Analysis

#### Objectives:
- To analyze the distribution of electric vehicle (EV) registrations across different states in the US.

- To examine the relationship between EV adoption and renewable energy production.

- To explore trends in EV registrations and energy generation over time.

- To identify states with high EV adoption and their corresponding energy sources.

- To analyze the correlation between EV growth and clean energy usage.

- To study the geographical distribution of EVs across the US.

- To uncover patterns that support the transition toward sustainable transportation.

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [12]:
ev_data = pd.read_excel("States_Electric_Vehicle_Registrations_2018.xlsx", header=2)
ev_data.head()

   Unnamed: 0       State  Registration Count  Unnamed: 3 Unnamed: 4
0         NaN     Alabama                1450         NaN        NaN
1         NaN      Alaska                 530         NaN        NaN
2         NaN     Arizona               15000         NaN        NaN
3         NaN    Arkansas                 520         NaN        NaN
4         NaN  California              256800         NaN        NaN

In [13]:
# Selecting relevant columns
ev_data = ev_data[['State', 'Registration Count']]

# Renaming columns
ev_data.columns = ['State', 'EV_Registrations']

# Removing missing values
ev_data = ev_data.dropna()

# Reset index
ev_data = ev_data.reset_index(drop=True)

# Preview cleaned data
ev_data.head()

        State  EV_Registrations
0     Alabama              1450
1      Alaska               530
2     Arizona             15000
3    Arkansas               520
4  California            256800

In [14]:
print("EV Data Columns:", ev_data.columns)

EV Data Columns: Index(['State', 'EV_Registrations'], dtype='object')

#### EV Data Cleaning

The EV dataset was cleaned by selecting relevant columns, renaming them for clarity and removing missing values. The final dataset provides state-wise electric vehicle registrations.

In [15]:
ev_data.shape

(52, 2)

In [16]:
ev_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   State             52 non-null     object
 1   EV_Registrations  52 non-null     int64
dtypes: int64(1), object(1)
memory usage: 964.0+ bytes

In [17]:
ev_data.describe()

       EV_Registrations
count         52.000000
mean       20908.076923
std        81965.026761
min          170.000000
25%         1037.500000
50%         3565.000000
75%         8717.500000
max       543610.000000

In [18]:
ev_data.isnull().sum()

State               0
EV_Registrations    0
dtype: int64

In [48]:
energy_data = pd.read_excel("States_Annual_Energy_Generation_Sources_1990_2019.xlsx", header=1)
energy_data.head()

,YEAR,STATE,TYPE OF PRODUCER,ENERGY SOURCE,GENERATION (Megawatthours)
0,1990,AK,Total Electric Power Industry,Total,5599506.0
1,1990,AK,Total Electric Power Industry,Coal,510573.0
2,1990,AK,Total Electric Power Industry,Hydroelectric Conventional,974521.0
3,1990,AK,Total Electric Power Industry,Natural Gas,3466261.0
4,1990,AK,Total Electric Power Industry,Petroleum,497116.0

In [49]:
# Keeping only required columns
energy_data = energy_data[['YEAR', 'STATE', 'ENERGY SOURCE', 'GENERATION (Megawatthours)']]

# Renaming columns
energy_data.columns = ['Year', 'State', 'Energy_Source', 'Energy_Generation']

# Remove missing values
energy_data = energy_data.dropna()

# Reset index
energy_data = energy_data.reset_index(drop=True)

# Preview cleaned data
energy_data.head()

   Year State               Energy_Source  Energy_Generation
0  1990    AK                       Total          5599506.0
1  1990    AK                        Coal           510573.0
2  1990    AK  Hydroelectric Conventional           974521.0
3  1990    AK                 Natural Gas          3466261.0
4  1990    AK                   Petroleum           497116.0

In [50]:
print("Energy Data Columns:", energy_data.columns)

Energy Data Columns: Index(['Year', 'State', 'Energy_Source', 'Energy_Generation'], dtype='object')

#### Energy Data Cleaning

The energy dataset is cleaned by selecting relevant columns and renaming them for clarity. Missing values were removed to ensure accurate analysis. The dataset now contains yearly energy generation by state and energy source.

In [51]:
energy_data.shape

(53756, 4)

In [52]:
energy_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53756 entries, 0 to 53755
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Year               53756 non-null  int64
 1   State              53756 non-null  object
 2   Energy_Source      53756 non-null  object
 3   Energy_Generation  53756 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.6+ MB

In [53]:
energy_data.describe()

               Year  Energy_Generation
count  53756.000000       5.375600e+04
mean    2005.518844       1.693131e+07
std        8.598414       1.309890e+08
min     1990.000000      -8.823445e+06
25%     1998.000000       2.684825e+04
50%     2006.000000       3.279665e+05
75%     2013.000000       3.405300e+06
max     2019.000000       4.178277e+09

In [54]:
energy_data.isnull().sum()

Year                 0
State                0
Energy_Source        0
Energy_Generation    0
dtype: int64

In [55]:
state_codes = pd.read_excel("state_codes.xlsx")
state_codes.head()

  state_code  state_name
0         AK      Alaska
1         AL     Alabama
2         AR    Arkansas
3         AZ     Arizona
4         CA  California

In [56]:
print("State Codes Columns:", state_codes.columns)

State Codes Columns: Index(['state_code', 'state_name'], dtype='object')

In [57]:
state_codes.shape

(51, 2)

In [58]:
state_codes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   state_code  51 non-null     object
 1   state_name  51 non-null     object
dtypes: object(2)
memory usage: 948.0+ bytes

In [59]:
state_codes.describe()

       state_code state_name
count          51         51
unique         51         51
top            AK     Alaska
freq            1          1

In [60]:
state_codes.isnull().sum()

state_code    0
state_name    0
dtype: int64

In [61]:
all_vehicles = pd.read_excel("States_All_Vehicle_Registrations_2018.xlsx", header=8)
all_vehicles.head(10)

,STATE,PRIVATE AND,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,COMMERCIAL,PUBLICLY,NaN,PRIVATE AND,PUBLICLY,NaN,PRIVATE AND,PUBLICLY,NaN,PRIVATE AND,PUBLICLY,NaN,PRIVATE AND,PUBLICLY,NaN
1,NaN,(INCLUDING,OWNED (1),TOTAL,COMMERCIAL,OWNED (1),TOTAL,COMMERCIAL,OWNED (1),TOTAL,COMMERCIAL,OWNED (1),TOTAL,COMMERCIAL,OWNED (1),TOTAL
2,NaN,TAXICABS),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Alabama,2116626,44586,2161212,5633.635236,132.974093,5766.609329,2955947,67261.40963,3023208.40963,109060,952.135108,110012.135108,5187266.635236,112932.518832,5300199.154068
4,Alaska,179131,4139,183270,7856,617.322626,8473.322626,563583,16807.236526,580390.236526,31542,8,31550,782112,21571.559152,803683.559152
5,Arizona,2372443,19329,2391772,1391.050584,6958.088141,8349.138725,3196426,39491.535925,3235917.535925,170271,3,170274,5740531.050584,65781.624066,5806312.674649
6,Arkansas,908561,12600,921161,11290.281712,715.885705,12006.167417,1765374,27477.128806,1792851.128806,91127,0,91127,2776352.281712,40793.01451,2817145.296223
7,California,14820833,244994,15065827,34437,65255.244456,99692.244456,14739522,294442.632872,15033964.632872,808889,13955,822844,30403681,618646.877329,31022327.877329
8,Colorado,1782358,15819,1798177,5718,7585.100032,13303.100032,3314999,38669.761806,3353668.761806,190735,134,190869,5293810,62207.861838,5356017.861838
9,Connecticut,1305544,1165,1306709,11717.810911,35.592047,11753.402959,1468599,5080.373267,1473679.373267,87640,19.77336,87659.77336,2873500.810911,6300.738674,2879801.549585

In [62]:
print("All Vehicles Columns:", all_vehicles.columns)

All Vehicles Columns: Index(['STATE', 'PRIVATE AND', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15'],
      dtype='object')

In [63]:
# Removing top unwanted rows
all_vehicles = all_vehicles.iloc[3:].reset_index(drop=True)

# Renaming first column as State
all_vehicles = all_vehicles.rename(columns={'STATE': 'State'})

# Extracting only State + last column (Total Vehicles)
all_vehicles_clean = all_vehicles[['State', all_vehicles.columns[-1]]]

# Renaming total column
all_vehicles_clean.columns = ['State', 'Total_Vehicles']

# Dropping missing values
all_vehicles_clean = all_vehicles_clean.dropna()

# Reset index
all_vehicles_clean = all_vehicles_clean.reset_index(drop=True)

# Preview
all_vehicles_clean.head()

         State   Total_Vehicles
0      Alabama   5300199.154068
1      Alaska     803683.559152
2      Arizona   5806312.674649
3     Arkansas   2817145.296223
4  California   31022327.877329

In [64]:
print("All Vehicles CLEAN Columns:", all_vehicles_clean.columns)

All Vehicles CLEAN Columns: Index(['State', 'Total_Vehicles'], dtype='object')

#### All Vehicles Data Cleaning

The dataset contained multiple header rows and complex structure. Relevant rows were extracted, and only total vehicle registrations per state were retained. The cleaned dataset now provides state-wise total vehicle counts.

In [65]:
all_vehicles_clean.shape

(52, 2)

In [66]:
all_vehicles_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State           52 non-null     object
 1   Total_Vehicles  52 non-null     object
dtypes: object(2)
memory usage: 964.0+ bytes

In [67]:
all_vehicles_clean.describe()

          State  Total_Vehicles
count        52    5.200000e+01
unique       52    5.200000e+01
top     Alabama    5.300199e+06
freq          1    1.000000e+00

In [68]:
all_vehicles_clean.isnull().sum()

State             0
Total_Vehicles    0
dtype: int64

## EV ANALYSIS

In [69]:
# EV Distribution Across States

ev_data = ev_data[ev_data['State'] != 'Total']
ev_sorted = ev_data.sort_values(by='EV_Registrations', ascending=False)

fig = px.bar(ev_sorted, x='State', y='EV_Registrations', title='EV Registrations by State',)
fig.show()

#### Insight-
The visualization shows a highly uneven distribution of electric vehicle registrations across states. California dominates EV adoption by a very large margin, Washington is the second-highest, but still significantly behind California. Most states have relatively low EV registrations, showing that EV adoption is still concentrated in a few regions. The large gap between top states and others highlights regional disparity in EV adoption.

## Energy Data Preparation

In [ ]:
# Filtering energy data for year 2018
energy_2018 = energy_data[energy_data['Year'] == 2018]

# Aggregate total energy per state (all sources combined)
energy_state = energy_2018.groupby('State')['Energy_Generation'].sum().reset_index()

# Preview
energy_state.head()

  State  Energy_Generation
0    AK         24989436.0
1    AL        580231978.0
2    AR        271997406.0
3    AZ        447700578.0
4    CA        781862553.0

In [74]:
# Converting state codes to full names
energy_state = pd.merge(energy_state, state_codes, left_on='State', right_on='state_code', how='left')

# Replacing code with full name
energy_state['State'] = energy_state['state_name']

# Keeping required columns
energy_state = energy_state[['State', 'Energy_Generation']]

# Preview
energy_state.head()

        State  Energy_Generation
0      Alaska         24989436.0
1     Alabama        580231978.0
2    Arkansas        271997406.0
3     Arizona        447700578.0
4  California        781862553.0

In [75]:
# Data Merging


merged_data = pd.merge(ev_data, energy_state, on='State', how='inner')
merged_data.head()

        State  EV_Registrations  Energy_Generation
0     Alabama              1450        580231978.0
1      Alaska               530         24989436.0
2     Arizona             15000        447700578.0
3    Arkansas               520        271997406.0
4  California            256800        781862553.0

## Correlation Analysis

#### Correlation Between EV Registrations and Energy Generation

In [76]:
fig = px.scatter(merged_data, x='Energy_Generation', y='EV_Registrations', hover_name='State', title='EV Registrations vs Energy Generation (2018)')
fig.show()

#### Insight-

- There is a general upward tendency: states with higher energy generation often have higher EV registrations, but the pattern is not strongly linear.
- A few states act as outliers:
  - One state (likely California) shows very high EV registrations relative to others.
  - Some states generate large amounts of energy but have comparatively low EV adoption.
- Most states are clustered at lower EV registration levels, even when energy generation varies widely.

In [77]:
merged_data[['EV_Registrations', 'Energy_Generation']].corr()

                   EV_Registrations  Energy_Generation
EV_Registrations           1.000000           0.314319
Energy_Generation          0.314319           1.000000


#### Conclusion:
The correlation coefficient between EV registrations and energy generation is approximately **0.31**. While energy availability contributes to EV adoption, it is not the primary driving factor. A combination of policy support, infrastructure, and socio-economic conditions is required to accelerate EV growth.

## TIME SERIES ANALYSIS

In [79]:
# Total energy per year
energy_yearly = energy_data.groupby('Year')['Energy_Generation'].sum().reset_index()

fig = px.line(energy_yearly, x='Year', y='Energy_Generation', title='Total Energy Generation Over Time')
fig.show()

#### Insight-

The line chart shows the trend of total energy generation from 1990 to 2019.

- There is a clear **long-term upward trend** from the early 1990s to the late 2000s, indicating sustained growth in energy production.
- Growth **slows and stabilizes after ~2008–2012**, with fluctuations around a relatively flat level.
- A noticeable **dip around 2008–2009** suggests the impact of external factors (e.g., economic slowdown).
- Post-2010, energy generation remains **stable with minor variations**, indicating a mature and balanced energy supply.

### SEASONAL TRENDS / LONG TERM SHIFTS

In [80]:
# Focusing on major energy sources
major_sources = ['Coal', 'Natural Gas', 'Hydroelectric Conventional', 'Wind', 'Solar']

energy_filtered = energy_data[energy_data['Energy_Source'].isin(major_sources)]
energy_trend = energy_filtered.groupby(['Year', 'Energy_Source'])['Energy_Generation'].sum().reset_index()

fig = px.line(energy_trend, x='Year', y='Energy_Generation', color='Energy_Source', title='Energy Generation by Source Over Time')
fig.show()

#### Insight-

This chart shows how different energy sources have changed over the years.

- Coal was the main source of energy earlier, but its use is decreasing over time.
- Natural gas is increasing steadily and has become one of the major energy sources.
- Hydroelectric energy remains mostly stable with small changes.
- Wind energy is growing, especially after 2010, but still lower than major sources.

## GEOSPATIAL ANALYSIS

In [84]:
# Top 10 states by EV registrations
top_states = ev_data.sort_values(by='EV_Registrations', ascending=False).head(10)

fig = px.bar(top_states, x='State', y='EV_Registrations',title='Top 10 States by EV Registrations')
fig.show()

#### Insight-

This chart shows the top 10 states with the highest number of EV registrations.

- California clearly leads with the highest EV registrations, far ahead of all other states.
- Washington is the second highest, but there is a large gap compared to California.
- States like Florida, Texas, and New York follow with moderate EV adoption.
- The remaining states in the top 10 have relatively similar and lower values.

## POLICY IMPACT ASSESSMENT

***Government policies play an important role in promoting electric vehicle adoption and clean energy usage.***

- States with higher EV adoption (such as California and Washington) are known for strong government support, incentives, and EV-friendly policies.
- Financial incentives like tax credits, subsidies, and rebates encourage people to buy electric vehicles.
- Investment in charging infrastructure makes EV usage more convenient and practical.
- Renewable energy policies support the growth of clean energy sources, which indirectly promotes EV adoption.

- Even though energy generation and EV adoption show some positive relationship, the correlation is weak.
- This indicates that **policies and infrastructure** are more important drivers than just energy availability.
- Government initiatives, incentives, and infrastructure development are key factors in increasing EV adoption and supporting sustainable transportation.

# Final Conclusion

- The dataset includes EV registrations and energy generation across US states.
- EV adoption is not equal in all states and is mainly higher in states like California.
- There is a small positive relationship between energy generation and EV registrations.
- Energy production has increased over the years but has become stable recently.
- There is a shift from coal to cleaner energy sources like wind and natural gas.
- Most states still have low EV adoption compared to a few leading states.


## Recommendations:

- Government should provide more incentives like subsidies and tax benefits for EVs.
- Charging stations should be increased to make EV usage easier.
- More focus should be given to clean and renewable energy sources.
- Awareness about EV benefits should be increased among people.
- States with low EV adoption should improve their policies by learning from leading states.


### Overall:
This project shows that EV adoption is growing but not evenly across all states. With better policies, infrastructure, and awareness, EV usage can increase and help in building a cleaner future.